esphome:
  name: $devicename
  platform: ESP32
  board: m5stack-core-esp32

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pw
  #domain: .jonn26.lan

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret esphome_rest_pw

ota:
  password: !secret esphome_ota_pw

sensor:
  - platform: wifi_signal
    name: "$upper_devicename WiFi Signal"
    update_interval: 60s

  - platform: uptime
    name: "$upper_devicename Uptime"

binary_sensor:
#Atom button
  - platform: gpio
    pin: GPIO39
    id: atom_button
    on_press:
      then:
      - light.toggle:
          id: mosfet
          transition_length: 300ms

  - platform: status
    name: $upper_devicename Status
    id: status_sensor

light:
  #atom neopixel led on the button
  - platform: neopixelbus
    type: GRB
    variant: SK6812
    pin: GPIO27
    num_leds: 1
    id: status_led
    restore_mode: ALWAYS_OFF

#atom pwm module https://shop.m5stack.com/products/atom-pwm-kit-fdd8447l
  - platform: monochromatic
    name: $upper_devicename
    id: mosfet
    output: gpio_22
    on_turn_on:
    - light.turn_on:
        id: status_led
        brightness: 50%
        red: 0%
        green: 100%
        blue: 0%
        transition_length: 300ms
    on_turn_off:
    - light.turn_on:
        id: status_led
        brightness: 50%
        red: 100%
        green: 0%
        blue: 0%
        transition_length: 300ms

#pwn on esp32 uses "ledc" platform per https://esphome.io/components/output/ledc.html?highlight=ledc
output:
  - platform: ledc
    id: gpio_22
    pin: GPIO22
    frequency: "9765Hz" #gives 13 bit depth per above URL
